language: node_js
node_js:
- "11"
- "10"
- "9"
- "8"
- "7"
- "6"

before_script:
  - npm install
  - npm run build

script:
  - npm run test

env:
- CC=clang CXX=clang++ npm_config_clang=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - build-essential
    - libudev-dev

